#coding:utf-8
# format settings
format:
 :csv_splitor: ';'
 
path:
 :demand_csv_path: 'uploadfiles/demands/csv'
 :demand_tmp_path: 'uploadfiles/demands/tmp'
 :dn_pdf_label_path: 'uploadfiles/dnLabelPdf'
 :printer_template_path: 'uploadfiles/printerTemplate'
page:
 :demand_page_size: 10

title:
 :demand_csv_title: ["PartNr","Supplier","Date","Type","Amount"]
 
resque:
 :resquedb: 0
 :resquehost: 127.0.0.1
 :resqueport: 6379
